/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as IndexImport } from './routes/index'
import { Route as AppStorageRouteImport } from './routes/app/storage/route'
import { Route as AppSettingsRouteImport } from './routes/app/settings/route'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard/route'
import { Route as AppAuthenticationRouteImport } from './routes/app/authentication/route'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppStorageRouteRoute = AppStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppSettingsRouteRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDashboardRouteRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppAuthenticationRouteRoute = AppAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => AppRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/app/authentication': {
      id: '/app/authentication'
      path: '/authentication'
      fullPath: '/app/authentication'
      preLoaderRoute: typeof AppAuthenticationRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/storage': {
      id: '/app/storage'
      path: '/storage'
      fullPath: '/app/storage'
      preLoaderRoute: typeof AppStorageRouteImport
      parentRoute: typeof AppRouteImport
    }
  }
}

// Create and export the route tree

interface AppRouteRouteChildren {
  AppAuthenticationRouteRoute: typeof AppAuthenticationRouteRoute
  AppDashboardRouteRoute: typeof AppDashboardRouteRoute
  AppSettingsRouteRoute: typeof AppSettingsRouteRoute
  AppStorageRouteRoute: typeof AppStorageRouteRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthenticationRouteRoute: AppAuthenticationRouteRoute,
  AppDashboardRouteRoute: AppDashboardRouteRoute,
  AppSettingsRouteRoute: AppSettingsRouteRoute,
  AppStorageRouteRoute: AppStorageRouteRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/app/authentication': typeof AppAuthenticationRouteRoute
  '/app/dashboard': typeof AppDashboardRouteRoute
  '/app/settings': typeof AppSettingsRouteRoute
  '/app/storage': typeof AppStorageRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/app/authentication': typeof AppAuthenticationRouteRoute
  '/app/dashboard': typeof AppDashboardRouteRoute
  '/app/settings': typeof AppSettingsRouteRoute
  '/app/storage': typeof AppStorageRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/app/authentication': typeof AppAuthenticationRouteRoute
  '/app/dashboard': typeof AppDashboardRouteRoute
  '/app/settings': typeof AppSettingsRouteRoute
  '/app/storage': typeof AppStorageRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-up'
    | '/app/authentication'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/storage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/sign-up'
    | '/app/authentication'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/storage'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-up'
    | '/app/authentication'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/storage'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SignUpRoute: typeof SignUpRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SignUpRoute: SignUpRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app": {
      "filePath": "app/route.tsx",
      "children": [
        "/app/authentication",
        "/app/dashboard",
        "/app/settings",
        "/app/storage"
      ]
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/app/authentication": {
      "filePath": "app/authentication/route.tsx",
      "parent": "/app"
    },
    "/app/dashboard": {
      "filePath": "app/dashboard/route.tsx",
      "parent": "/app"
    },
    "/app/settings": {
      "filePath": "app/settings/route.tsx",
      "parent": "/app"
    },
    "/app/storage": {
      "filePath": "app/storage/route.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
